### ISSUE TITLE
Works not with debian jessie due of missing method basename in stdlib

### ISSUE THREAD

**Issue by bschatz** [Yuav/puppet-autofs#6]
More a hint than a issue:
puppet-autofs needs the method basename from puppet stdlib
added with stdlib version 4.6.
But current version in debian jessie is 4.3.2.

You could add this as a hint to the docu "limitations".

==>
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function basename at /etc/puppet/modules/autofs/manifests/mount.pp:11 on node .....

**Comment by Yuav** [comment]
Thank you for reporting this. The issue is actually not local to Debian, as stdlib is usually installed from Puppet forge, and not apt repositories. The modulefile.json did however list a too old version of stdlib in dependencies. I have updated this now. Also, I have added Debian to the acceptance tests - which are successfully executed
